import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const ninjaFont = localFont({
  src: "../public/njnaruto.ttf",
  variable: "--font-ninja",
});

export const metadata: Metadata = {
  title: "Naruto",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={ninjaFont.variable}>{children}</body>
    </html>
  );
}
